[tool.black]
line-length = 120
target-version = ['py310', 'py311']

[tool.ruff]
line-length = 120
target-version = "py310"
select = ["ALL"]
fixable = ["ALL"]
fix = true
ignore = ["D211", "D212", "T201", "NPY002", "FBT001", "N806", "N803", "PLW0603", "PTH123", "B905", "ANN003", "ANN002", "SIM115"]

[tool.mypy]
python_version = "3.10"
strict = true
ignore_missing_imports = true
exclude = "venv"